server:
  port: 8080
  servlet:
    context-path: /

spring:
  application.name: chat-api
  datasource:
    driverClassName: org.postgresql.Driver
    hikari:
      pool-name: chat-api-dbconnectionpool
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: validate
---

spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://chat-api-postgres:5432/chat
    username: postgres
    password: postgres
server:
  port: 8090

---

spring:
  config:
    activate:
      on-profile: test
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test_db
  flyway:
    enabled: false
  jpa:
    show-sql: false
    database: h2
    hibernate:
      ddl-auto: create-drop
logging:
  level:
    root: error